/**
 * This file was automatically generated by GraphQL Nexus
 * Do not make changes to this file directly
 */

import * as ctx from "../src/context"
import * as prisma from "./prisma-client/index"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  ItemWhereInput: { // input type
    AND?: NexusGenInputs['ItemWhereInput'][] | null; // [ItemWhereInput!]
    field?: string | null; // String
    field_contains?: string | null; // String
    field_ends_with?: string | null; // String
    field_gt?: string | null; // String
    field_gte?: string | null; // String
    field_in?: string[] | null; // [String!]
    field_lt?: string | null; // String
    field_lte?: string | null; // String
    field_not?: string | null; // String
    field_not_contains?: string | null; // String
    field_not_ends_with?: string | null; // String
    field_not_in?: string[] | null; // [String!]
    field_not_starts_with?: string | null; // String
    field_starts_with?: string | null; // String
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    secondItems_some?: NexusGenInputs['SecondItemWhereInput'] | null; // SecondItemWhereInput
  }
  SecondItemWhereInput: { // input type
    AND?: NexusGenInputs['SecondItemWhereInput'][] | null; // [SecondItemWhereInput!]
    id?: string | null; // ID
    id_contains?: string | null; // ID
    id_ends_with?: string | null; // ID
    id_gt?: string | null; // ID
    id_gte?: string | null; // ID
    id_in?: string[] | null; // [ID!]
    id_lt?: string | null; // ID
    id_lte?: string | null; // ID
    id_not?: string | null; // ID
    id_not_contains?: string | null; // ID
    id_not_ends_with?: string | null; // ID
    id_not_in?: string[] | null; // [ID!]
    id_not_starts_with?: string | null; // ID
    id_starts_with?: string | null; // ID
    mySuperSearch?: string | null; // String
    secondField?: string | null; // String
    secondField_contains?: string | null; // String
    secondField_ends_with?: string | null; // String
    secondField_gt?: string | null; // String
    secondField_gte?: string | null; // String
    secondField_in?: string[] | null; // [String!]
    secondField_lt?: string | null; // String
    secondField_lte?: string | null; // String
    secondField_not?: string | null; // String
    secondField_not_contains?: string | null; // String
    secondField_not_ends_with?: string | null; // String
    secondField_not_in?: string[] | null; // [String!]
    secondField_not_starts_with?: string | null; // String
    secondField_starts_with?: string | null; // String
  }
}

export interface NexusGenEnums {
  SecondItemOrderByInput: prisma.SecondItemOrderByInput
}

export interface NexusGenRootTypes {
  Item: prisma.Item;
  Query: {};
  SecondItem: prisma.SecondItem;
  String: string;
  Int: number;
  Float: number;
  Boolean: boolean;
  ID: string;
}

export interface NexusGenAllTypes extends NexusGenRootTypes {
  ItemWhereInput: NexusGenInputs['ItemWhereInput'];
  SecondItemWhereInput: NexusGenInputs['SecondItemWhereInput'];
  SecondItemOrderByInput: NexusGenEnums['SecondItemOrderByInput'];
}

export interface NexusGenFieldTypes {
  Item: { // field return type
    field: string; // String!
    id: string; // ID!
    secondItems: NexusGenRootTypes['SecondItem'][] | null; // [SecondItem!]
  }
  Query: { // field return type
    items: NexusGenRootTypes['Item'][]; // [Item!]!
  }
  SecondItem: { // field return type
    id: string; // ID!
    secondField: string | null; // String
  }
}

export interface NexusGenArgTypes {
  Item: {
    secondItems: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
      orderBy?: NexusGenEnums['SecondItemOrderByInput'] | null; // SecondItemOrderByInput
      skip?: number | null; // Int
      where?: NexusGenInputs['SecondItemWhereInput'] | null; // SecondItemWhereInput
    }
  }
  Query: {
    items: { // args
      where?: NexusGenInputs['ItemWhereInput'] | null; // ItemWhereInput
    }
  }
}

export interface NexusGenAbstractResolveReturnTypes {
}

export interface NexusGenInheritedFields {}

export type NexusGenObjectNames = "Item" | "Query" | "SecondItem";

export type NexusGenInputNames = "ItemWhereInput" | "SecondItemWhereInput";

export type NexusGenEnumNames = "SecondItemOrderByInput";

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = "Boolean" | "Float" | "ID" | "Int" | "String";

export type NexusGenUnionNames = never;

export interface NexusGenTypes {
  context: ctx.Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  allTypes: NexusGenAllTypes;
  inheritedFields: NexusGenInheritedFields;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractResolveReturn: NexusGenAbstractResolveReturnTypes;
}